version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 792850570647.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t docker-test .
      - docker tag docker-test:latest 792850570647.dkr.ecr.us-west-2.amazonaws.com/docker-test:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 792850570647.dkr.ecr.us-west-2.amazonaws.com/docker-test:latest
