version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 840532010037.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t sonarqube .
      - docker tag docker tag sonarqube:latest 840532010037.dkr.ecr.us-west-2.amazonaws.com/sonarqube:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 840532010037.dkr.ecr.us-west-2.amazonaws.com/sonarqube:latest
